name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

    - name: Save Docker image to a file
      run: |
        docker save myapp:latest | gzip > myapp.tar.gz

    - name: Upload Docker image to repository root
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: myapp.tar.gz
